---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n266021/public_html/
    - /bin/rsync -av / $DEPLOYPATH
    - name: Log de implementación
      command: |
        echo "$(date '+%H:%M:%S') - \"$(git log --format='%s' -n 1)\"" >> $DEPLOYPATH/deploy.log

