---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html
    - /bin/cp -r * $DEPLOYPATH
    - name: Log de implementación
      command: |
        echo "$(date '+%H:%M:%S') - \"$(git log --format='%s' -n 1)\"" >> $DEPLOYPATH/deploy.log
